<analytic>
	<analytic>.daas.python.reExecuteNoArgs</analytic>
	<code_text>{[udfName;err]
	
    if[err like "* positional arguments but 2 were given";
        :@[.daas.udf.udfFuncStore[x]`func;::;{.log.warn[`udfExecution;"UDF ",string[x]," failed to execute with error";y]}[udfName;]]
        ];

    .log.warn[`udfExecution;"UDF ",string[x]," failed to execute with error";err];
	}</code_text>
	<description></description>
	<dictionaryparams>0</dictionaryparams>
	<typ>Analytic</typ>
	<private>0</private>
	<returntype></returntype>
	<returndata></returndata>
	<defaultconnection></defaultconnection>
	<alias></alias>
	<analytictype></analytictype>
	<returndescription></returndescription>
	<param>
		<parameter>udfName</parameter>
		<default></default>
		<description>default parameter</description>
		<required>1</required>
		<datatype>Symbol</datatype>
	</param>
	<param>
		<parameter>err</parameter>
		<default></default>
		<description>default parameter</description>
		<required>1</required>
		<datatype>Symbol</datatype>
	</param>
	<analyticgroup>daasPython</analyticgroup>
</analytic>
